---
title: "deep_goon_price_prediction"
output: html_document
date: "2024-02-22"
---

```{r setup, include=FALSE}
library(dplyr)
```

```{r}
# Set the path to the directory containing the CSV files
path_to_data <- "data_schedule/"

# List all CSV files in the directory
file_list <- list.files(path = path_to_data, pattern = "*.csv", full.names = TRUE)

# Define a function to read and process each CSV file
process_csv <- function(file_name) {
  df <- read.csv(file_name)
  
  # Optionally, add a source file column to identify the data's origin
  df$source_file <- basename(file_name)
  
  return(df)
}

# Read all CSV files into a list of data frames
schedule_list <- lapply(file_list, process_csv)

# Find the intersection of all column names across all data frames
common_columns <- Reduce(intersect, lapply(schedule_list, names))

# Keep only the common columns in each data frame and combine
schedule_list <- lapply(schedule_list, `[`, common_columns)
schedule <- do.call(rbind, schedule_list)
schedule$source_file <- NULL

# Check the combined data frame
print(schedule)
```

```{r}
# Set the path to the directory containing the CSV files
path_to_data <- "data_sales/"

# List all CSV files in the directory
file_list <- list.files(path = path_to_data, pattern = "*.csv", full.names = TRUE)

# Define a function to read and process each CSV file
process_csv <- function(file_name) {
  df <- read.csv(file_name)
  
  # Optionally, add a source file column to identify the data's origin
  df$source_file <- basename(file_name)
  
  return(df)
}

# Read all CSV files into a list of data frames
sales_list <- lapply(file_list, process_csv)

# Find the intersection of all column names across all data frames
common_columns <- Reduce(intersect, lapply(sales_list, names))

# Keep only the common columns in each data frame and combine
sales_list <- lapply(sales_list, `[`, common_columns)

sales <- do.call(rbind, sales_list)
sales$source_file <- NULL

# Check the combined data frame
print(sales)

```



```{r}
#schedule_12 <- read.csv('data_schedule/2022_Schedule_info.csv')
schedule$Date <- as.Date(schedule$Date, format = "%m/%d/%Y")
#ticketing <- read.csv('data_sales/2022_Ticketing_Data.csv')
sales$Date <- as.Date(sales$Date, format = "%Y-%m-%d")
df <- left_join(sales, schedule,by = "Date")
write.csv(df,"combined_data.csv")
```

```{r}
str(df)
summary(df)
```

```{r}
hist(sales$Tickets, main = "Distribution of Tickets", xlab = "Tickets", col = "blue")
```

